### ISSUE TITLE
`minitouch did not work`

### ISSUE THREAD

**Issue by williamfzc** [williamfzc/pyminitouch#11]
TODO

**Comment by aphkyle** [comment]
Hello, I'm having a problem running the example code,
I'm using device product:a30czh model:SM_A3050 device:a30c transport_id:1

Here's the code:
`from pyminitouch import MNTDevice


_DEVICE_ID = 'R28M616KB2E'
device = MNTDevice(_DEVICE_ID)

# single-tap
device.tap([(400, 600)])
# multi-tap
device.tap([(400, 400), (600, 600)])
# set the pressure, default == 100
device.tap([(400, 600)], pressure=50)

# 可以直接用简洁的API调用minitouch提供的强大功能！

# 在使用完成后，需要显式调用stop方法将服务停止
device.stop()`
Here's the full error log:
`2021-06-19 18:17:24.360 | INFO     | pyminitouch.utils:is_device_connected:56 - device SM-A3050 online
2021-06-19 18:17:24.371 | INFO     | pyminitouch.connection:__init__:87 - searching a usable port ...
2021-06-19 18:17:26.390 | INFO     | pyminitouch.connection:__init__:89 - device R28M616KB2E bind to port 20878
2021-06-19 18:17:26.720 | INFO     | pyminitouch.connection:get_abi:35 - device R28M616KB2E is arm64-v8a
2021-06-19 18:17:26.987 | INFO     | pyminitouch.connection:__init__:27 - minitouch already existed in R28M616KB2E
2021-06-19 18:17:27.002 | DEBUG    | pyminitouch.connection:_forward_port:128 - forward command: adb -s R28M616KB2E forward tcp:20878 localabstract:minitouch     
2021-06-19 18:17:27.247 | DEBUG    | pyminitouch.connection:_forward_port:130 - output: b'20878\r\n'
2021-06-19 18:17:27.270 | INFO     | pyminitouch.connection:_start_mnt:141 - start minitouch: adb -s R28M616KB2E shell /data/local/tmp/minitouch
open: Permission denied
Unable to open device /dev/input/event1 for inspectionopen: Permission denied
Unable to open device /dev/input/mouse0 for inspectionopen: Permission denied
Unable to open device /dev/input/event12 for inspectionopen: Permission denied
Unable to open device /dev/input/event11 for inspectionopen: Permission denied
Unable to open device /dev/input/event7 for inspectionopen: Permission denied
Unable to open device /dev/input/event3 for inspectionopen: Permission denied
Unable to open device /dev/input/event10 for inspectionopen: Permission denied
Unable to open device /dev/input/event2 for inspectionopen: Permission denied
Unable to open device /dev/input/event6 for inspectionopen: Permission denied
Unable to open device /dev/input/event9 for inspectionopen: Permission denied
Unable to open device /dev/input/event0 for inspectionopen: Permission denied
Unable to open device /dev/input/event5 for inspectionopen: Permission denied
Unable to open device /dev/input/mice for inspectionopen: Permission denied
Unable to open device /dev/input/event8 for inspectionopen: Permission denied
Unable to open device /dev/input/event4 for inspectionUnable to find a suitable touch device
Traceback (most recent call last):
  File "c:\coding\test.py", line 5, in <module>
    device = MNTDevice(_DEVICE_ID)
  File "C:\Users\kaph\AppData\Local\Programs\Python\Python39\lib\site-packages\pyminitouch\actions.py", line 117, in __init__
    self.start()
  File "C:\Users\kaph\AppData\Local\Programs\Python\Python39\lib\site-packages\pyminitouch\actions.py", line 125, in start
    self.server = MNTServer(self.device_id)
  File "C:\Users\kaph\AppData\Local\Programs\Python\Python39\lib\site-packages\pyminitouch\connection.py", line 101, in __init__
    assert (
AssertionError: minitouch did not work. see https://github.com/williamfzc/pyminitouch/issues/11`
any idea why is it not working? Thanks.

**Comment by aphkyle** [comment]
Hi I'm having trouble running the example code.
I'm plugging in SAMSUNG A3050
```py
from pyminitouch import MNTDevice


_DEVICE_ID = 'R28M616KB2E'
device = MNTDevice(_DEVICE_ID)

# single-tap
device.tap([(400, 600)])
# multi-tap
device.tap([(400, 400), (600, 600)])
# set the pressure, default == 100
device.tap([(400, 600)], pressure=50)

# 可以直接用简洁的API调用minitouch提供的强大功能！

# 在使用完成后，需要显式调用stop方法将服务停止
device.stop()
```
The error log is:
```bash
2021-06-19 18:17:24.360 | INFO     | pyminitouch.utils:is_device_connected:56 - device SM-A3050 online
2021-06-19 18:17:24.371 | INFO     | pyminitouch.connection:__init__:87 - searching a usable port ...
2021-06-19 18:17:26.390 | INFO     | pyminitouch.connection:__init__:89 - device R28M616KB2E bind to port 20878
2021-06-19 18:17:26.720 | INFO     | pyminitouch.connection:get_abi:35 - device R28M616KB2E is arm64-v8a
2021-06-19 18:17:26.987 | INFO     | pyminitouch.connection:__init__:27 - minitouch already existed in R28M616KB2E
2021-06-19 18:17:27.002 | DEBUG    | pyminitouch.connection:_forward_port:128 - forward command: adb -s R28M616KB2E forward tcp:20878 localabstract:minitouch     
2021-06-19 18:17:27.247 | DEBUG    | pyminitouch.connection:_forward_port:130 - output: b'20878\r\n'
2021-06-19 18:17:27.270 | INFO     | pyminitouch.connection:_start_mnt:141 - start minitouch: adb -s R28M616KB2E shell /data/local/tmp/minitouch
open: Permission denied
Unable to open device /dev/input/event1 for inspectionopen: Permission denied
Unable to open device /dev/input/mouse0 for inspectionopen: Permission denied
Unable to open device /dev/input/event12 for inspectionopen: Permission denied
Unable to open device /dev/input/event11 for inspectionopen: Permission denied
Unable to open device /dev/input/event7 for inspectionopen: Permission denied
Unable to open device /dev/input/event3 for inspectionopen: Permission denied
Unable to open device /dev/input/event10 for inspectionopen: Permission denied
Unable to open device /dev/input/event2 for inspectionopen: Permission denied
Unable to open device /dev/input/event6 for inspectionopen: Permission denied
Unable to open device /dev/input/event9 for inspectionopen: Permission denied
Unable to open device /dev/input/event0 for inspectionopen: Permission denied
Unable to open device /dev/input/event5 for inspectionopen: Permission denied
Unable to open device /dev/input/mice for inspectionopen: Permission denied
Unable to open device /dev/input/event8 for inspectionopen: Permission denied
Unable to open device /dev/input/event4 for inspectionUnable to find a suitable touch device
Traceback (most recent call last):
  File "c:\Users\kylec\OneDrive\Documents\cool\fuckallgames\fuckbrawlstars\test2.py", line 5, in <module>
    device = MNTDevice(_DEVICE_ID)
  File "C:\Users\kylec\AppData\Local\Programs\Python\Python39\lib\site-packages\pyminitouch\actions.py", line 117, in __init__
    self.start()
  File "C:\Users\kylec\AppData\Local\Programs\Python\Python39\lib\site-packages\pyminitouch\actions.py", line 125, in start
    self.server = MNTServer(self.device_id)
  File "C:\Users\kylec\AppData\Local\Programs\Python\Python39\lib\site-packages\pyminitouch\connection.py", line 101, in __init__
    assert (
AssertionError: minitouch did not work. see https://github.com/williamfzc/pyminitouch/issues/11
```
Any idea how to fix it?

**Comment by chenzhiron** [comment]
可以打开任务管理器，查看是否有 adb 进程，手动关闭该进程，再次重试即可解决
可能出现的问题是在调试阶段，代码出错时的中断退出，导致adb没有被自动关闭
