### ISSUE TITLE
minitouch did not work

### ISSUE THREAD

**Issue by hakaboom** [williamfzc/pyminitouch#13]
![error](https://user-images.githubusercontent.com/43911741/103152546-02bc7780-47c4-11eb-9b82-5de7d997941a.png)
也尝试过adb重启,但是依旧会显示minitouch did not work.
pyminitouch可以和uiautomator2一同运行吗

**Comment by hakaboom** [comment]
```
2020-12-26 21:40:25.192 | INFO     | pyminitouch.utils:is_device_connected:56 - device V1936A online
2020-12-26 21:40:25.192 | INFO     | pyminitouch.connection:__init__:87 - searching a usable port ...
2020-12-26 21:40:27.193 | INFO     | pyminitouch.connection:__init__:89 - device emulator-5554 bind to port 20210
2020-12-26 21:40:27.219 | INFO     | pyminitouch.connection:get_abi:35 - device emulator-5554 is x86
2020-12-26 21:40:27.236 | INFO     | pyminitouch.connection:__init__:27 - minitouch already existed in emulator-5554
2020-12-26 21:40:27.236 | DEBUG    | pyminitouch.connection:_forward_port:128 - forward command: adb -s emulator-5554 forward tcp:20210 localabstract:minitouch
2020-12-26 21:40:27.247 | DEBUG    | pyminitouch.connection:_forward_port:130 - output: b''
2020-12-26 21:40:27.247 | INFO     | pyminitouch.connection:_start_mnt:141 - start minitouch: adb -s emulator-5554 shell /data/local/tmp/minitouch
Traceback (most recent call last):
  File "C:/Users/27070/Desktop/python/test/main.py", line 6, in <module>
    device = MNTDevice(_DEVICE_ID)
  File "C:\Users\27070\AppData\Local\Programs\Python\Python38\lib\site-packages\pyminitouch\actions.py", line 117, in __init__
    self.start()
  File "C:\Users\27070\AppData\Local\Programs\Python\Python38\lib\site-packages\pyminitouch\actions.py", line 125, in start
    self.server = MNTServer(self.device_id)
  File "C:\Users\27070\AppData\Local\Programs\Python\Python38\lib\site-packages\pyminitouch\connection.py", line 101, in __init__
    assert (
AssertionError: minitouch did not work. see https://github.com/williamfzc/pyminitouch/issues/11

```

**Comment by williamfzc** [comment]
确实不能一起用，因为uiautomator2也用了minitouch（虽然我不知道用这个干嘛，它似乎没有这种场景
