### ISSUE TITLE
执行examples的draw_heart报错

### ISSUE THREAD

**Issue by hsevenh** [williamfzc/pyminitouch#14]
报错如下：
`2021-01-20 14:20:56.757 | INFO     | pyminitouch.utils:is_device_connected:56 - device SM-N9100 online
2021-01-20 14:20:56.757 | INFO     | pyminitouch.connection:__init__:87 - searching a usable port ...
2021-01-20 14:20:58.758 | INFO     | pyminitouch.connection:__init__:89 - device 477bc861 bind to port 20233
2021-01-20 14:20:59.121 | INFO     | pyminitouch.connection:get_abi:35 - device 477bc861 is armeabi-v7a

2021-01-20 14:20:59.396 | INFO     | pyminitouch.connection:__init__:27 - minitouch already existed in 477bc861
2021-01-20 14:20:59.396 | DEBUG    | pyminitouch.connection:_forward_port:128 - forward command: adb -s 477bc861 forward tcp:20233 localabstract:minitouch
2021-01-20 14:20:59.599 | DEBUG    | pyminitouch.connection:_forward_port:130 - output: b'20233\r\n'
2021-01-20 14:20:59.599 | INFO     | pyminitouch.connection:_start_mnt:141 - start minitouch: adb -s 477bc861 shell /data/local/tmp/minitouch
Traceback (most recent call last):
  File "D:\新建文件夹\pyminitouch-master\pyminitouch-master\examples\draw_heart.py", line 6, in <module>
    with safe_connection(_DEVICE_ID) as connection:
  File "C:\Program Files\Python37\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\Users\ayyk\AppData\Roaming\Python\Python37\site-packages\pyminitouch\connection.py", line 209, in safe_connection
    server = MNTServer(device_id)
  File "C:\Users\ayyk\AppData\Roaming\Python\Python37\site-packages\pyminitouch\connection.py", line 103, in __init__
    ), "minitouch did not work. see https://github.com/williamfzc/pyminitouch/issues/11"
AssertionError: minitouch did not work. see https://github.com/williamfzc/pyminitouch/issues/11
[Finished in 5.2s]`

用CMD做了这两步也没有作用。
adb kill-server
adb start-server

**Comment by williamfzc** [comment]
是不是跟 uiautomator2 一起用了

**Comment by hsevenh** [comment]
感谢回复，已经解决了。
是那个自动push 的minitouch的问题。我自己重新找了minitouch 手动push以后就可以了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "williamfzc/pyminitouch"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月22日(星期五) 中午11:26
收件人:&nbsp;"williamfzc/pyminitouch"<pyminitouch@noreply.github.com&gt;;
抄送:&nbsp;"风居住的街道"<894717809@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [williamfzc/pyminitouch] 执行examples的draw_heart报错 (#14)





 
是不是跟 uiautomator2 一起用了

**Comment by r-luo** [comment]
> 感谢回复，已经解决了。 是那个自动push 的minitouch的问题。我自己重新找了minitouch 手动push以后就可以了。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "williamfzc/pyminitouch" <notifications@github.com&gt;; 发送时间:&nbsp;2021年1月22日(星期五) 中午11:26 收件人:&nbsp;"williamfzc/pyminitouch"<pyminitouch@noreply.github.com&gt;; 抄送:&nbsp;"风居住的街道"<894717809@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [williamfzc/pyminitouch] 执行examples的draw_heart报错 (#14) 是不是跟 uiautomator2 一起用了 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

您好，我现在遇到了同样的问题，想问一下手动push 具体是怎么做的。。？
