### ISSUE TITLE
minitouch did not work. see https://github.com/williamfzc/pyminitouch/issues/11  怎么解决呢？

### ISSUE THREAD

**Issue by gavin231mao** [williamfzc/pyminitouch#15]
C:\Users\gavin\.conda\envs\PyTorch19_GPU_Py38\python.exe "D:/@3 深度学习/案例/@6 WZCQ-main 用强化学习训练AI玩王者荣耀/WZCQ-main/训练数据截取_A.py"
loading pretrained weights...
2021-07-08 13:56:06.226 | INFO     | pyminitouch.utils:is_device_connected:56 - device oneplus a5010 online
2021-07-08 13:56:06.226 | INFO     | pyminitouch.connection:__init__:87 - searching a usable port ...
2021-07-08 13:56:08.227 | INFO     | pyminitouch.connection:__init__:89 - device 127.0.0.1:7555 bind to port 20315
2021-07-08 13:56:08.270 | INFO     | pyminitouch.connection:get_abi:35 - device 127.0.0.1:7555 is x86

2021-07-08 13:56:08.301 | INFO     | pyminitouch.connection:__init__:27 - minitouch already existed in 127.0.0.1:7555
2021-07-08 13:56:08.301 | DEBUG    | pyminitouch.connection:_forward_port:128 - forward command: adb -s 127.0.0.1:7555 forward tcp:20315 localabstract:minitouch
2021-07-08 13:56:08.325 | DEBUG    | pyminitouch.connection:_forward_port:130 - output: b''
2021-07-08 13:56:08.325 | INFO     | pyminitouch.connection:_start_mnt:141 - start minitouch: adb -s 127.0.0.1:7555 shell /data/local/tmp/minitouch
Traceback (most recent call last):
  File "D:/@3 深度学习/案例/@6 WZCQ-main 用强化学习训练AI玩王者荣耀/WZCQ-main/训练数据截取_A.py", line 192, in <module>
    设备 = MyMNTDevice(_DEVICE_ID)
  File "D:\@3 深度学习\案例\@6 WZCQ-main 用强化学习训练AI玩王者荣耀\WZCQ-main\运行辅助.py", line 8, in __init__
    MNTDevice.__init__(self,ID)
  File "C:\Users\gavin\.conda\envs\PyTorch19_GPU_Py38\lib\site-packages\pyminitouch\actions.py", line 117, in __init__
    self.start()
  File "C:\Users\gavin\.conda\envs\PyTorch19_GPU_Py38\lib\site-packages\pyminitouch\actions.py", line 125, in start
    self.server = MNTServer(self.device_id)
  File "C:\Users\gavin\.conda\envs\PyTorch19_GPU_Py38\lib\site-packages\pyminitouch\connection.py", line 101, in __init__
    assert (
AssertionError: minitouch did not work. see https://github.com/williamfzc/pyminitouch/issues/11

**Comment by williamfzc** [comment]
https://github.com/williamfzc/pyminitouch/issues/11
