### ISSUE TITLE
open: Permission denied, AssertionError: minitouch did not work.

### ISSUE THREAD

**Issue by Core2002** [williamfzc/pyminitouch#16]
```
2021-08-26 13:14:52.978 | INFO     | pyminitouch.utils:is_device_connected:56 - device PACM00 online
2021-08-26 13:14:52.980 | INFO     | pyminitouch.connection:__init__:87 - searching a usable port ...
2021-08-26 13:14:54.993 | INFO     | pyminitouch.connection:__init__:89 - device CUPRKJKVU4MR8HIJ bind to port 20040
2021-08-26 13:14:55.127 | INFO     | pyminitouch.connection:get_abi:35 - device CUPRKJKVU4MR8HIJ is arm64-v8a
2021-08-26 13:14:55.321 | INFO     | pyminitouch.connection:get_abi:35 - device CUPRKJKVU4MR8HIJ is arm64-v8a
2021-08-26 13:14:55.324 | INFO     | pyminitouch.connection:download_target_mnt:41 - target minitouch url: https://github.com/williamfzc/stf-binaries/raw/master/node_modules/minitouch-prebuilt/prebuilt/arm64-v8a/bin/minitouch
C:\Users\core2\AppData\Local\Temp\tmpi_2zkvss: 1 file pushed, 0 skipped. 4.9 MB/s (34736 bytes in 0.007s)
2021-08-26 13:14:57.541 | INFO     | pyminitouch.connection:download_target_mnt:51 - minitouch already installed in /data/local/tmp/minitouch
2021-08-26 13:14:57.544 | DEBUG    | pyminitouch.connection:_forward_port:128 - forward command: adb -s CUPRKJKVU4MR8HIJ forward tcp:20040 localabstract:minitouch
2021-08-26 13:14:57.615 | DEBUG    | pyminitouch.connection:_forward_port:130 - output: b'20040\r\n'
2021-08-26 13:14:57.617 | INFO     | pyminitouch.connection:_start_mnt:141 - start minitouch: adb -s CUPRKJKVU4MR8HIJ shell /data/local/tmp/minitouch
open: Permission denied
Unable to open device /dev/input/event3 for inspectionopen: Permission denied
Unable to open device /dev/input/event0 for inspectionopen: Permission denied
Unable to open device /dev/input/event2 for inspectionopen: Permission denied
Unable to open device /dev/input/event1 for inspectionUnable to find a suitable touch device
Traceback (most recent call last):
  File "run.py", line 5, in <module>
    device = MNTDevice('CUPRKJKVU4MR8HIJ')
  File "C:\Users\core2\anaconda3\lib\site-packages\pyminitouch\actions.py", line 117, in __init__
    self.start()
  File "C:\Users\core2\anaconda3\lib\site-packages\pyminitouch\actions.py", line 125, in start
    self.server = MNTServer(self.device_id)
  File "C:\Users\core2\anaconda3\lib\site-packages\pyminitouch\connection.py", line 101, in __init__
    assert (
AssertionError: minitouch did not work. see https://github.com/williamfzc/pyminitouch/issues/11

```

> OPPO R15

**Comment by williamfzc** [comment]
https://github.com/openstf/minitouch/issues/41

**Comment by Anychnn** [comment]
有个疑问，这个是因为手机没有root权限吗, 我无法通过adb 访问 /data目录

**Comment by williamfzc** [comment]
- 可能跟系统有关，可以先尝试：https://github.com/williamfzc/pyminitouch/issues/18#issuecomment-1374846827
- 访问不到 /data 也正常，但一般可以访问到 /data/local/tmp

**Comment by Anychnn** [comment]
你好， ?xml:namespace>

**Comment by Anychnn** [comment]
你好， ?xml:namespace>
