### ISSUE TITLE
运行报错，错误如下

### ISSUE THREAD

**Issue by csh159** [williamfzc/pyminitouch#2]
Traceback (most recent call last):
  File "demo.py", line 7, in <module>
    device = MNTDevice(_DEVICE_ID)
  File "C:\Users\dennis\Desktop\pyminitouch-master\pyminitouch\actions.py", line 45, in __init__
    server = MNTServer(device_id)
  File "C:\Users\dennis\Desktop\pyminitouch-master\pyminitouch\connection.py", line 78, in __init__
    assert self.heartbeat()
AssertionError

**Comment by williamfzc** [comment]
前面的日志可以一并截下吗？类似：

```
2019-01-03 10:37:02.578 | INFO     | pyminitouch.utils:is_device_connected:46 - device PBDM00 online
2019-01-03 10:37:02.579 | INFO     | pyminitouch.connection:__init__:64 - searching a usable port ...
2019-01-03 10:37:03.618 | INFO     | pyminitouch.connection:__init__:66 - device 1234 bind to port 20237
2019-01-03 10:37:04.384 | INFO     | pyminitouch.connection:get_abi:27 - device 1234 is arm64-v8a
2019-01-03 10:37:04.695 | INFO     | pyminitouch.connection:__init__:21 - minitouch already existed in 1234
```

**Comment by csh159** [comment]
全部日志如下：

C:\Users\dennis\Desktop\pyminitouch-master>python demo.py
2019-01-03 10:33:22.049 | INFO     | pyminitouch.utils:is_device_connected:46 - device vivo y55a online
2019-01-03 10:33:22.052 | INFO     | pyminitouch.connection:__init__:64 - searching a usable port ...
2019-01-03 10:33:23.060 | INFO     | pyminitouch.connection:__init__:66 - device emulator-5554 bind to port 20216
2019-01-03 10:33:23.131 | INFO     | pyminitouch.connection:get_abi:27 - device emulator-5554 is x86

2019-01-03 10:33:23.191 | INFO     | pyminitouch.connection:__init__:21 - minitouch already existed in emulator-5554
2019-01-03 10:33:23.193 | INFO     | pyminitouch.connection:_forward_port:100 - forward command: D:\Android\android-sdk\platform-tools\adb.exe -s emulator-5554 forward tcp:20216 localabstract:minitouch
2019-01-03 10:33:23.224 | INFO     | pyminitouch.connection:_start_mnt:109 - start minitouch: D:\Android\android-sdk\platform-tools\adb.exe -s emulator-5554 shell /data/local/tmp/minitouch
Traceback (most recent call last):
  File "demo.py", line 7, in <module>
    device = MNTDevice(_DEVICE_ID)
  File "C:\Users\dennis\Desktop\pyminitouch-master\pyminitouch\actions.py", line 45, in __init__
    server = MNTServer(device_id)
  File "C:\Users\dennis\Desktop\pyminitouch-master\pyminitouch\connection.py", line 78, in __init__
    assert self.heartbeat()
AssertionError

**Comment by csh159** [comment]
单独执行minitouch文件的话报错：C:\Users\dennis\Desktop\pyminitouch-master>adb shell /data/local/tmp/minitouch -h
/data/local/tmp/minitouch[1]: syntax error: 'newline' unexpected

**Comment by williamfzc** [comment]
看起来是minitouch版本不对，或者可能是minitouch本身对模拟器的支持不好导致的。
这个minitouch是你自己装的吗？还是pyminitouch自动装的呢？

**Comment by csh159** [comment]
在别的地方下了一个minitouch push进去就可以运行了，不报错，自动下载安装地址的minitouch有问题

**Comment by csh159** [comment]
问一下这个坐标不是手机的左上角0，0开始的坐标系吗？device.tap([(5000, 5000)])这样子才能点击到屏幕中间大概的位置

**Comment by williamfzc** [comment]
minitouch的操作区域可能与手机本身分辨率不一致：

> It's also very important to note that the maximum X and Y coordinates may, but usually do not, match the display size. You'll need to work out a good way to map display coordinates to touch coordinates if required, possibly by using percentages for screen coordinates.

但就目前我接触到的机器而言，感觉真机上表现还算正常。如果有真机的话优先用真机试一下？

**Comment by gdzhczx** [comment]
你好，我自己push的minitouch，还是不可以运行呀，报错和帖主一样

**Comment by williamfzc** [comment]
> 你好，我自己push的minitouch，还是不可以运行呀，报错和帖主一样

参考下他的方式解决呢，minitouch的版本有不少，要跟你的系统一致才行
https://github.com/openatx/stf-binaries/tree/master/node_modules/minitouch-prebuilt/prebuilt

**Comment by gdzhczx** [comment]
大佬，我发现好像minitouch也出了问题，之前可以push的，现在push不上去了。
![image](https://user-images.githubusercontent.com/68729104/154221350-1edac2d8-7802-4349-b62f-2d83203efce8.png)
为什么push成功了文件夹里却看不到minitouch呢？非常的迷幻

**Comment by williamfzc** [comment]
> 大佬，我发现好像minitouch也出了问题，之前可以push的，现在push不上去了。 ![image](https://user-images.githubusercontent.com/68729104/154221350-1edac2d8-7802-4349-b62f-2d83203efce8.png) 为什么push成功了文件夹里却看不到minitouch呢？非常的迷幻

用 adb shell 登进去看看那个目录里是什么情况，可能被重命名成tmp文件了

**Comment by gdzhczx** [comment]
> > 大佬，我发现好像minitouch也出了问题，之前可以push的，现在push不上去了。 ![image](https://user-images.githubusercontent.com/68729104/154221350-1edac2d8-7802-4349-b62f-2d83203efce8.png) 为什么push成功了文件夹里却看不到minitouch呢？非常的迷幻
> 
> 用 adb shell 登进去看看那个目录里是什么情况，可能被重命名成tmp文件了

这个图里面有我登进去后的效果呀，tmp文件夹里就一个mini文件

**Comment by williamfzc** [comment]
文件叫mini，赋权命令写的又是minitouch，当然没有
